# Generated by Django 3.0.4 on 2020-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200501_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarwidget',
            name='abstract',
        ),
        migrations.AlterField(
            model_name='sidebarwidget',
            name='body',
            field=models.TextField(),
        ),
    ]
