# Generated by Django 3.0.4 on 2020-05-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidebarwidget_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarwidget',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sidebarwidget',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
