# Generated by Django 3.0.4 on 2020-07-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200706_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a banner image.', upload_to='headerImg/%Y/%m/%d/'),
        ),
    ]
