# Generated by Django 3.0.4 on 2020-05-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200501_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarwidget',
            name='image',
        ),
    ]
