# Generated by Django 3.0.4 on 2020-06-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200608_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='navigation_topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='SideBarWidget',
        ),
    ]
