# Generated by Django 3.0.4 on 2020-06-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200610_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(limit_choices_to=4, to='blog.Navigation_topics'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=150),
        ),
    ]
