# Generated by Django 3.0.4 on 2020-06-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200610_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation_topics',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(limit_choices_to=4, to='blog.Navigation_topics'),
        ),
        migrations.AlterField(
            model_name='navigation_topics',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
