# Generated by Django 3.0.4 on 2020-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200610_2317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='navigation_topics',
            new_name='Navigation_topic',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
    ]
