# Generated by Django 3.0.4 on 2020-06-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200610_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags_1',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
