# Generated by Django 3.0.4 on 2020-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200610_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags_1',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(to='blog.Navigation_topic'),
        ),
    ]
