# Generated by Django 3.0.4 on 2020-06-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200610_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation_topic',
            name='link_status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags_1',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
    ]
