# Generated by Django 3.0.4 on 2020-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200611_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation_topic',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags_1',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='posts', to='blog.Tags'),
        ),
    ]
