# Generated by Django 3.0.4 on 2020-05-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='posts',
        ),
    ]
