# Generated by Django 3.0.4 on 2020-05-21 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_user_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
