# Generated by Django 3.0.4 on 2020-05-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_user_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='slug',
        ),
    ]
