# Generated by Django 3.0.4 on 2020-05-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_user_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(default='  ', max_length=150),
        ),
    ]
