import { doc, setDoc } from 'firebase/firestore'
import { db } from '../lib/firebase'

const DEMO_PROVIDERS = [
  {
    id: 'demo-provider-001',
    name: 'Dr. Amara Nkosi',
    type: 'Psychiatrist',
    hpcsa: 'MP0234567',
    avatar: '🧠',
    specialties: ['ADHD', 'Anxiety', 'Depression', 'Bipolar Disorder'],
    bio: 'Board-certified psychiatrist with 12 years of experience in adult and adolescent mental health. I take an integrative approach combining psychopharmacology with practical therapeutic strategies, helping patients build sustainable routines and emotional resilience.',
    experience: '12',
    languages: ['English', 'Zulu'],
    city: 'Johannesburg',
    province: 'Gauteng',
    sessionFee: 1800,
    availability: 'Mon to Fri, 9am to 4pm SAST',
    meetingPlatform: 'zoom',
    meetingLink: '',
    timezone: 'South Africa (SAST, UTC+2)',
    subscriptionActive: true,
    subscriptionPlan: 'featured',
    subscriptionStarted: '2024-01-15T08:00:00.000Z',
    profileViews: 142,
    ratingCount: 8,
    ratingAvg: { communication: 4.6, empathy: 4.8, professionalism: 4.7, treatmentPlan: 4.5, overall: 4.7 },
    diary: {
      mon: ['09:00', '10:00', '11:00', '14:00', '15:00'],
      tue: ['09:00', '10:00', '14:00', '15:00'],
      wed: ['09:00', '10:00', '11:00'],
      thu: ['09:00', '10:00', '14:00', '15:00', '16:00'],
      fri: ['09:00', '10:00', '11:00'],
    },
  },
  {
    id: 'demo-provider-002',
    name: 'Dr. Pieter van der Berg',
    type: 'Psychologist',
    hpcsa: 'PS0345678',
    avatar: '🌿',
    specialties: ['ADHD', 'Stress Management', 'Anxiety', 'Executive Function'],
    bio: 'Clinical psychologist specialising in ADHD assessment and coaching for adults. My evidence-based approach draws from CBT and DBT frameworks to help clients manage executive function challenges, build self-regulation skills, and thrive in work and relationships.',
    experience: '9',
    languages: ['English', 'Afrikaans'],
    city: 'Cape Town',
    province: 'Western Cape',
    sessionFee: 1500,
    availability: 'Mon to Thu, 8am to 5pm SAST',
    meetingPlatform: 'meet',
    meetingLink: '',
    timezone: 'South Africa (SAST, UTC+2)',
    subscriptionActive: true,
    subscriptionPlan: 'standard',
    subscriptionStarted: '2024-02-01T08:00:00.000Z',
    profileViews: 98,
    ratingCount: 5,
    ratingAvg: { communication: 4.4, empathy: 4.2, professionalism: 4.6, treatmentPlan: 4.3, overall: 4.4 },
    diary: {
      mon: ['08:00', '09:00', '10:00', '14:00'],
      tue: ['08:00', '09:00', '11:00', '15:00'],
      wed: ['10:00', '11:00'],
      thu: ['09:00', '10:00', '14:00', '15:00', '16:00'],
    },
  },
  {
    id: 'demo-provider-003',
    name: 'Dr. Naledi Dlamini',
    type: 'Psychiatrist',
    hpcsa: 'MP0456789',
    avatar: '💙',
    specialties: ['Depression', 'Anxiety', 'PTSD', 'Trauma'],
    bio: 'Psychiatrist with a special interest in trauma-informed care and mood disorders. With 15 years in clinical practice, I provide compassionate, culturally sensitive care for adults navigating depression, PTSD, and complex trauma.',
    experience: '15',
    languages: ['English', 'Sotho', 'Zulu'],
    city: 'Pretoria',
    province: 'Gauteng',
    sessionFee: 2000,
    availability: 'Tue to Fri, 9am to 3pm SAST',
    meetingPlatform: 'zoom',
    meetingLink: '',
    timezone: 'South Africa (SAST, UTC+2)',
    subscriptionActive: true,
    subscriptionPlan: 'featured',
    subscriptionStarted: '2024-01-20T08:00:00.000Z',
    profileViews: 211,
    ratingCount: 12,
    ratingAvg: { communication: 4.9, empathy: 4.9, professionalism: 4.8, treatmentPlan: 4.7, overall: 4.9 },
    diary: {
      tue: ['09:00', '10:00', '11:00'],
      wed: ['09:00', '10:00', '11:00', '14:00'],
      thu: ['09:00', '10:00', '14:00', '15:00'],
      fri: ['09:00', '10:00'],
    },
  },
  {
    id: 'demo-provider-004',
    name: 'Dr. Kobus Steyn',
    type: 'Psychologist',
    hpcsa: 'PS0567890',
    avatar: '🔬',
    specialties: ['ADHD', 'Autism Spectrum', 'Executive Function', 'Sleep Disorders'],
    bio: 'Clinical neuropsychologist focusing on neurodevelopmental conditions in adults. I provide comprehensive ADHD and autism spectrum assessments, skills-based coaching, and psycho-education to help clients understand their neurology and unlock their potential.',
    experience: '7',
    languages: ['English', 'Afrikaans'],
    city: 'Durban',
    province: 'KwaZulu-Natal',
    sessionFee: 1400,
    availability: 'Mon to Fri, 8am to 4pm SAST',
    meetingPlatform: 'teams',
    meetingLink: '',
    timezone: 'South Africa (SAST, UTC+2)',
    subscriptionActive: true,
    subscriptionPlan: 'standard',
    subscriptionStarted: '2024-03-10T08:00:00.000Z',
    profileViews: 74,
    ratingCount: 3,
    ratingAvg: { communication: 4.3, empathy: 4.0, professionalism: 4.5, treatmentPlan: 4.1, overall: 4.2 },
    diary: {
      mon: ['08:00', '09:00', '10:00', '11:00'],
      tue: ['08:00', '09:00', '14:00', '15:00'],
      wed: ['08:00', '09:00', '10:00', '14:00'],
      thu: ['08:00', '09:00', '10:00'],
      fri: ['08:00', '09:00'],
    },
  },
  {
    id: 'demo-provider-005',
    name: 'Dr. Thandi Molefe',
    type: 'Psychiatrist',
    hpcsa: 'MP0678901',
    avatar: '🌸',
    specialties: ['Bipolar Disorder', 'OCD', 'Anxiety', 'Life Transitions'],
    bio: 'I am a psychiatrist dedicated to holistic mental wellness, with expertise in mood disorders, OCD, and life transitions. I believe in collaborative care, working with each patient to find the right combination of medication, lifestyle, and therapeutic support.',
    experience: '10',
    languages: ['English', 'Tswana', 'Sotho'],
    city: 'Johannesburg',
    province: 'Gauteng',
    sessionFee: 1700,
    availability: 'Mon, Wed, Fri, 10am to 5pm SAST',
    meetingPlatform: 'zoom',
    meetingLink: '',
    timezone: 'South Africa (SAST, UTC+2)',
    subscriptionActive: true,
    subscriptionPlan: 'standard',
    subscriptionStarted: '2024-02-15T08:00:00.000Z',
    profileViews: 130,
    ratingCount: 6,
    ratingAvg: { communication: 4.5, empathy: 4.7, professionalism: 4.4, treatmentPlan: 4.6, overall: 4.5 },
    diary: {
      mon: ['10:00', '11:00', '14:00', '15:00'],
      wed: ['10:00', '11:00', '14:00'],
      fri: ['10:00', '11:00', '12:00', '14:00', '15:00'],
    },
  },
  {
    id: 'demo-provider-006',
    name: 'Dr. Sarah Chen',
    type: 'Psychologist',
    hpcsa: 'PS0789012',
    avatar: '☀️',
    specialties: ['Anxiety', 'Depression', 'Stress Management', 'PTSD'],
    bio: 'CBT and ACT therapist with a warm, practical approach to anxiety and depression. I work with adults experiencing burnout, chronic stress, and low mood to rebuild meaning and momentum in their lives. Sessions are solution-focused and skills-driven.',
    experience: '6',
    languages: ['English', 'Mandarin', 'Xhosa'],
    city: 'Cape Town',
    province: 'Western Cape',
    sessionFee: 1200,
    availability: 'Mon to Fri, 9am to 6pm SAST',
    meetingPlatform: 'whereby',
    meetingLink: '',
    timezone: 'South Africa (SAST, UTC+2)',
    subscriptionActive: true,
    subscriptionPlan: 'standard',
    subscriptionStarted: '2024-04-01T08:00:00.000Z',
    profileViews: 58,
    ratingCount: 4,
    ratingAvg: { communication: 4.8, empathy: 4.9, professionalism: 4.6, treatmentPlan: 4.5, overall: 4.7 },
    diary: {
      mon: ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00'],
      tue: ['09:00', '10:00', '14:00', '15:00', '16:00'],
      wed: ['09:00', '10:00', '11:00', '14:00'],
      thu: ['09:00', '10:00', '14:00', '15:00'],
      fri: ['09:00', '10:00', '11:00'],
    },
  },
]

export async function seedDemoProviders() {
  const results = []
  for (const { id, ...data } of DEMO_PROVIDERS) {
    try {
      await setDoc(doc(db, 'providers', id), {
        ...data,
        isDemo: true,
        seededAt: new Date().toISOString(),
      })
      results.push({ id, name: data.name, success: true })
    } catch (e) {
      results.push({ id, name: data.name, success: false, error: e.message })
    }
  }
  return results
}
